name = "conigail-modpack"
version = "0.1.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "578595446357108da61cb78f7e280e1814acaafeecf0598a4b539d7fb55ab83a"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
