name = "conigail-modpack"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "add57c2fbf01c6737b45136306d43ba0f1b0a29756855f3103812c579b315ecd"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
