name = "conigail-modpack"
version = "0.1.25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "730576bbf04c573ddfd4bd3f585fad8320dbdca621727402387faed97b7a1a64"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
