name = "conigail-modpack"
version = "0.2.25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f516d95d7b8a3447f27c27f0d54a3382a94e5b2b3d73f78ce2911b10e2f42f30"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
