name = "conigail-modpack"
version = "0.1.34"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c78b57c0bc49130b43458040b3cfd352ff3ec7ee9c906ef289d80fefb90b4a3"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
