name = "conigail-modpack"
version = "0.2.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec160d71966eae7991b9e34b812fcbfbb41b49949b43c6a0d4a2ac5baa066299"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
