name = "Conigail Modpack"
author = "abbydiode"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fa40f05973725b43ddf83303593fa98828ec9b61db0310e443dffcf6290273a"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
