name = "conigail-modpack"
version = "0.1.33"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b62244fdb9bfd43d60ff7da0eb77fd9060cca6489d8c422df8d392af0ca3ef99"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
