name = "conigail-modpack"
version = "0.1.36"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbe2792729fafc9f7265515c29c67d531031c3f0e2c3043fc1c1ac803062792a"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
