name = "conigail-modpack"
version = "0.1.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30d34d3f066951aae46a84d85bf481f9695f8cbcbf46b12d392d79d3e693bac1"

[versions]
minecraft = "1.19"
fabric = "0.14.8"
