name = "conigail-modpack"
version = "0.1.32"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "668b7ba67955aa18d97b9dbe4aa21c0e412d4bee9b51aee49b1003d6a0b299a6"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
