name = "Conigail Modpack"
author = "abbydiode"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e96ecfad93cb499221bede1edfaa8a349658e8ce01e6cc1ce4b2b1ade3d88ad"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
