name = "Conigail Modpack"
author = "abbydiode"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d39b08f984957ccc9e850d1f02a21ff07958efa4dd7fcd7fec8910bb4ab2b816"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
