name = "conigail-modpack"
author = "abbydiode"
version = "0.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29a6bc323cedb09d10511d42e5ff5036b087bf326edd9c6a5dbdb4f21aa0fd8d"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
