name = "conigail-modpack"
version = "0.2.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dce0cb7dd0cb16b7c53a5b1fda7bbd240930f54050e9d54d14f0033760d760f1"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
