name = "Conigail Modpack"
author = "abbydiode"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9b329f6fc80e7116f95239095f9242b2b61933fa10a50e02e584011f5afaa4b"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
